### ISSUE TITLE
安卓项目运行加载so库的时候就报错

### ISSUE THREAD

**Issue by darkSuperman** [moli232777144/seetaface2_demo#1]
作者你好:
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "atof" referenced by "libFaceDetectorJni.so"...
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                     at java.lang.System.loadLibrary(System.java:526)
                                                     at com.seeta.sdk.FaceDetector2.<clinit>(FaceDetector2.java:7)
                                                     at com.seetaface2as.DetectionActivity.onCreate(DetectionActivity.java:96)
。。。。。
你自己成功跑过这个安卓测试demo吗？好像是seetaface  so文件本身的问题，我用官方的自己捣鼓跑也是报这个加载so库出错

**Comment by moli232777144** [comment]
第一版是正常的，但速度明显达不到说明文档的速度，第二版so加载就有问题，之前去官方反馈过，没回复。

**Comment by JamesLiAndroid** [comment]
我这边用android6.0的机器测了一下，初始化容易闪退，但是没有错误日志打出来！

授权后，重新打开可用！
